### ISSUE TITLE
PRECISA DE CORREÇÃO

### ISSUE THREAD

**Issue by evssousa** [PauloLimaj/projeto4-viage-a-fernando-de-noronha#1]
Prestar atenção no nome dos repositórios, devem está **IGUAL** aos dos projetos.

**Comment by PauloLima4** [comment]
Já alterei nome e fiz algumas mudanças no código :D

**Comment by evssousa** [comment]
Continua com nome "projeto4-viage-a-fernando-de-noronha". Não adicionar "projetoX"

**Comment by PauloLima4** [comment]
CORRIGIDO
